### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by accetone** [lobo-studio/cabinet-guy.fr#2]
@bolom 
I need following images:
1) Original header images for desktop and mobile
2) Certificate icon (honoraires section) 2x size
3) Phone icon (contact section) 2x size

I have some problems with images when export from Avocode. I asked Ondrej in basecamp for these, but not sure if he receive my messages. Maybe you have some other method to contact with him.

**Comment by bolom** [comment]
@accetone  basecamp is the best place
