### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by accetone** [lobo-studio/cabinet-guy.fr#3]
@bolom can you take a look at http://cabinet-guy.fr/public/ and send me your feedback, please?

**Comment by bolom** [comment]
The email works ?

**Comment by accetone** [comment]
@bolom Contactez-moi ?

**Comment by bolom** [comment]
Yes

**Comment by accetone** [comment]
@bolom we need some backend code for this feature. Can you provide me http endpoint so I can call it from js?

**Comment by bolom** [comment]
Can we use that ?

https://formkeep.com/guides/contact-form-jekyll

**Comment by bolom** [comment]
It's super expensive. What do you think will be the best solution and safe ?
You can create a small backend node to send the email no?
